theme:
  name: 'material'

site_name: Curso Kubernetes

nav:
- Readme: README.md
- Modulo1:
  - Implantacion Aplic Web: modulo1/implantacion-aplic-web.md
  - Docker: modulo1/docker.md
  - Orquestadores: modulo1/orquestadores.md
  - Proyecto Kubernetes: modulo1/proyecto-kubernetes.md
  - Arquitectura: modulo1/arquitectura.md
- Modulo2:
  - Alternativas: modulo2/alternativas.md
  - Instalacion Kubectl Linux: modulo2/instalacion-kubectl-linux.md
  - Instalacion Kubectl Windows: modulo2/instalacion-kubectl-windows.md
  - Instalacion Minikube Linux: modulo2/instalacion-minikube-linux.md
  - Instalacion Minikube Windows: modulo2/instalacion-minikube-windows.md
  - Instalacion Minikube: modulo2/instalacion-minikube.md
  - Despliegues K8S: modulo2/despliegues-k8s.md
  - Actividad1: modulo2/actividad1.md  
- Modulo3:
  - Pods: modulo3/pods.md
  - Describiendo Pod: modulo3/describiendo_pod.md
  - Gestionando Pod: modulo3/gestionando_pod.md
  - Actividad1: modulo3/actividad1.md
  - Actividad2: modulo3/actividad2.md  
- Modulo4:
  - Replicaset: modulo4/replicaset.md
  - Describiendo Replicaset: modulo4/describiendo_replicaset.md
  - Gestionando Replicaset: modulo4/gestionando_replicaset.md
  - Actividad1: modulo4/actividad1.md  
- Modulo5:
  - Deployment: modulo5/deployment.md
  - Describiendo Deployment: modulo5/describiendo_deployment.md
  - Gestionando Deployment: modulo5/gestionando_deployment.md  
  - Actualizacion Deployment: modulo5/actualizacion_deployment.md
  - Actividad1: modulo5/actividad1.md
  - Actividad2: modulo5/actividad2.md
  - Actividad3: modulo5/actividad3.md  
- Modulo6:
  - Services: modulo6/services.md
  - Describiendo Services: modulo6/describiendo_services.md
  - Gestionando Services: modulo6/gestionando_services.md  
  - Dns: modulo6/dns.md
  - Ingress: modulo6/ingress.md
  - Temperaturas: modulo6/temperaturas.md
  - Actividad1: modulo6/actividad1.md
  - Actividad2: modulo6/actividad2.md  
- Modulo7:
  - Variables Entorno: modulo7/variables_entorno.md
  - Configmaps: modulo7/configmaps.md
  - Secrets: modulo7/secrets.md
  - Wordpress: modulo7/wordpress.md
  - Actividad1: modulo7/actividad1.md
  - Actividad2: modulo7/actividad2.md  
- Modulo8:
  - Consideraciones: modulo8/consideraciones.md
  - Volumenes: modulo8/volumenes.md
  - Aprovisionamiento: modulo8/aprovisionamiento.md
  - Solicitud: modulo8/solicitud.md
  - Uso: modulo8/uso.md
  - Ejemplo1: modulo8/ejemplo1.md
  - Ejemplo2: modulo8/ejemplo2.md  
  - Wordpress: modulo8/wordpress.md
  - Actividad1: modulo8/actividad1.md
  - Actividad2: modulo8/actividad2.md
  - Actividad3: modulo8/actividad3.md  
- Modulo9:
  - Otras Cargas: modulo9/otras_cargas.md
  - Statefulsets: modulo9/statefulsets.md    
  - Ejemplo2: modulo9/ejemplo2.md
  - Daemonsets: modulo9/daemonsets.md  
  - Jobs: modulo9/jobs.md  
  - Actividad1: modulo9/actividad1.md  
- Modulo10:
  - Helm: modulo10/helm.md  
  - Instalacion: modulo10/instalacion.md  
  - Ejemplo: modulo10/ejemplo.md
  - Actividad1: modulo10/actividad1.md
theme:
  name: material
